version: '3.7'

services:
  web:
    container_name: inj-nginx
    image: nginx:1.17.7
    ports:
      - 5820:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d:cached
      - ./src:/var/www/html:cached

  app:
    container_name: inj-app
    build:
      context: .
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  database:
    image: mysql:8
    ports:
      - 3720:3306
    container_name: inj-database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_USER=inj_user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=inj_db"
      - "MYSQL_ROOT_PASSWORD=jkhefg876@m%"
